// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXhy2SPt9P6RDIbFn-XmV6bd7TCrlQuog',
    appId: '1:1077218641144:web:d137d4af916551ba55a70d',
    messagingSenderId: '1077218641144',
    projectId: 'shop-prueba-189ee',
    authDomain: 'shop-prueba-189ee.firebaseapp.com',
    storageBucket: 'shop-prueba-189ee.firebasestorage.app',
    measurementId: 'G-QH0NNKCKYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5rjP4MmSAL0iD6YLATC64PrvntcnnyU',
    appId: '1:1077218641144:android:e01922178c3727c855a70d',
    messagingSenderId: '1077218641144',
    projectId: 'shop-prueba-189ee',
    storageBucket: 'shop-prueba-189ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCncjvuI5YQhTd1I_KKOqROemW5t3Gku5s',
    appId: '1:1077218641144:ios:d493f31ebc1bd5ec55a70d',
    messagingSenderId: '1077218641144',
    projectId: 'shop-prueba-189ee',
    storageBucket: 'shop-prueba-189ee.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCncjvuI5YQhTd1I_KKOqROemW5t3Gku5s',
    appId: '1:1077218641144:ios:d493f31ebc1bd5ec55a70d',
    messagingSenderId: '1077218641144',
    projectId: 'shop-prueba-189ee',
    storageBucket: 'shop-prueba-189ee.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXhy2SPt9P6RDIbFn-XmV6bd7TCrlQuog',
    appId: '1:1077218641144:web:b641a1ff15cda2c855a70d',
    messagingSenderId: '1077218641144',
    projectId: 'shop-prueba-189ee',
    authDomain: 'shop-prueba-189ee.firebaseapp.com',
    storageBucket: 'shop-prueba-189ee.firebasestorage.app',
    measurementId: 'G-VH58ESDBWC',
  );
}
